name: CI

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"
    paths-ignore:
      - "README.md"
      - ".gitignore"

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Format check
      run: make fmt
    - name: Linting check
      run: make lint

  test:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Test
      run: make test
